### ISSUE TITLE
Issues running example

### ISSUE THREAD

**Issue by CamJW101** [Pandapip1/mineflayer-swarm#1]
Hello! I love the idea behind this but am having issues running the basic example...

When I run the echo example, I run into these errors.

```
UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'inject_allowed' of undefined
    at EventEmitter.<anonymous> (/root/servers/node_modules/mineflayer-swarm/index.js:79:24)
    at EventEmitter.emit (events.js:400:28)
    at EventEmitter.bot.emit (/root/servers/node_modules/mineflayer-swarm/index.js:27:13)
    at Client.next (/root/servers/node_modules/mineflayer/lib/loader.js:124:9)
    at Object.onceWrapper (events.js:519:28)
    at Client.emit (events.js:400:28)
    at /root/servers/node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
    at /root/servers/node_modules/minecraft-protocol/src/ping.js:13:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
```
swarm.bots = swarm.bots.filter(x => bot.username !== x.username)
                                            ^

TypeError: Cannot read property 'username' of undefined
    at /root/servers/node_modules/mineflayer-swarm/index.js:74:45
    at Array.filter (<anonymous>)
```
Any thoughts? Thanks!

**Comment by Pandapip1** [comment]
Yea, this is still very much WIP. I'll fix it right now!

**Comment by Pandapip1** [comment]
This *should* be fixed. If not, I would check your authorizations.

**Comment by CamJW101** [comment]
I'll check it right now! Great stuff!
